### ISSUE TITLE
Import and Export USFM / USFX / USX

### ISSUE THREAD

**Issue by jamescmarsh** [schierlm/BibleMultiConverter#15]
I specifically am interested in converting MyBibleZone files to USFM or something similar, like USFX or USX.

**Comment by schierlm** [comment]
Have a look at the current implementation if it suffices your needs. In case you need more / anything else, feel free to reopen.

**Comment by AlisterH** [comment]
Hi, how do you actually export to USFM? For other formats you add an output filename to the end of the command to avoid the error message as per #13, but I can't work out what to do for usfm.
````
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1

**Comment by shadow-light** [comment]
Thanks for this great tool. I was also confused by the traceback from missing an arg since it wasn't clear what the problem was. I thought it was an issue parsing the file. Perhaps the exception can be caught and "Argument missing" or something printed instead?

```
WARNING: Skipping unknown tag \fig
WARNING: Skipping unknown end tag \fig*
WARNING: Skipping mismatched end tag \fig*
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doExportBooks(AbstractParatextFormat.java:430)
        at biblemulticonverter.tools.ParatextConverter.run(ParatextConverter.java:41)
        at biblemulticonverter.Main.main(Main.java:58)
```
