### ISSUE TITLE
Conversion of Hebrew and Greek Bibles

### ISSUE THREAD

**Issue by WJSwanepoel** [schierlm/BibleMultiConverter#6]
Hi,
I am trying to convert Hebrew and Greek Bibles and BibleMultiConverter crashes on this error:

C:\MBC>java -jar BibleMultiConverter.jar MyBibleZone HSB4.SQLite3 TheWord HSB4
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.substring(Unknown Source)
        at biblemulticonverter.sqlite.format.MyBibleZone.doImport(MyBibleZone.java:177)
        at biblemulticonverter.Main.main(Main.java:61)

Am I doing something wrong?

Regards,
Willem

**Comment by schierlm** [comment]
Hello Willem,

Thank you for the bug report. 

Currently the MyBible importer assumes that the book abbreviation (`short_name` in books table) contains at least one Latin letter, as it is used to build the book abbreviation (TheWord is one of the few export formats that don't care about the book abbreviation). I will fix this by using a default abbreviation for the book if there are no Latin letters in the abbreviation.

Regards,

Michael
