### ISSUE TITLE
Error converting USFM -> USX3

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#64]
Sorry another issue today :)

Getting this error come up when converting [this USFM](https://ebible.org/Scriptures/mpp_usfm.zip) to USX3. I'm not sure whether its because the USFM has invalid markup or whether its something else...

It seems to not like `lemma="ngic hae-gba"` as part of a `\w` tag?

```
Error: Command failed: java "-Dbiblemulticonverter.paratext.usx.verseseparatortext= " -jar BibleMultiConverter.jar ParatextConverter USFM "sources/mpp_wbt/usfm" USX3 "dist/bibles/mpp_wbt/usx" "*.usx"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:BibleMultiConverter/lib/jaxb-impl-2.2.11.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" javax.xml.bind.MarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-pattern-valid: Value 'ngic hae-gba' is not facet-valid with respect to pattern '\S+' for type 'NonEmptyOrBlankString'.]
        at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:326)
        at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:251)
        at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:138)
        at biblemulticonverter.format.paratext.USX3.doExportBook(USX3.java:386)
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doExportBooks(AbstractParatextFormat.java:435)
        at biblemulticonverter.tools.ParatextConverter.run(ParatextConverter.java:41)
        at biblemulticonverter.Main.main(Main.java:58)
Caused by: org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-pattern-valid: Value 'ngic hae-gba' is not facet-valid with respect to pattern '\S+' for type 'NonEmptyOrBlankString'.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:511)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3587)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processOneAttribute(XMLSchemaValidator.java:3107)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:3051)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2286)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:829)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
        at com.sun.xml.bind.v2.runtime.output.SAXOutput.endStartTag(SAXOutput.java:128)
        at com.sun.xml.bind.v2.runtime.output.ForkXmlOutput.endStartTag(ForkXmlOutput.java:106)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.endAttributes(XMLSerializer.java:307)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:592)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:341)
        at com.sun.xml.bind.v2.runtime.property.ArrayReferenceNodeProperty.serializeListBody(ArrayReferenceNodeProperty.java:118)
        at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:159)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:360)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:696)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementNodeProperty.serializeItem(ArrayElementNodeProperty.java:69)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementProperty.serializeListBody(ArrayElementProperty.java:172)
        at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:159)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:360)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:593)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:341)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:494)
        at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:323)
        ... 6 more
```

**Comment by schierlm** [comment]
Ah, it seems that the final USX3 schema allows whitespace in lemmas. Will push a commit today that updates the schema embedded in BibleMultiConverter to allow that too.

As a workaround, you could also use `-Dbiblemulticonverter.skipxmlvalidation=true` option (at the risk that the tool might output invalid XML).

**Comment by schierlm** [comment]
Good luck with your project!

If you are looking for some more recent/popular freely-licensed German translations:
- [Leonberger Bibel](https://causamundi.de/shop/page.php?p=bible.php) is a literal translation licensed CC-BY-NC-ND (where you can even choose if you prefer Nestle-Aland or Robinson-Pierpont source text), which also includes Strongs references and morphology information for (almost) every word.
- [Offene Bibel](https://www.offene-bibel.de) is a community translation licensed CC-BY-SA 3.0 (which is still quite incomplete)
- [NeÜ](https://www.derbibelvertrauen.de/) is a modern bible translation, where while not being CC licensed it it is quite easy to obtain permission for distribution of the bible text free of charge (see [terms and conditions in English](https://www.derbibelvertrauen.de/images/Publikationen/Freeware/Freeware-Vertrag-KHV-englisch.pdf)).

The pages linked above are in German but probably easy enough to understand after machine translation. If you are not interested in these texts, that's fine too. It is probably easier to get the number of languges up than getting quality translations in less-niche languages.

**Comment by shadow-light** [comment]
Thanks Michael, that's really helpful, it would be great to have some modern German Bibles added
