### ISSUE TITLE
Getting exception errors

### ISSUE THREAD

**Issue by paul1149** [schierlm/BibleMultiConverter#70]
I'm trying to convert a TheWord New Testament file to MyBible for Android, using BMC 0.0.8. This is the output I get:

$ java -jar BMC.jar TheWord k16.nt MyBibleZone
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at biblemulticonverter.sqlite.format.MyBibleZone.doExport(MyBibleZone.java:603)
	at biblemulticonverter.Main.main(Main.java:67)

I had done this previously with no problem, but since then I've done editing on the NT file. I have no idea what is causing this error. Any help would be appreciated. Great prog!

**Comment by schierlm** [comment]
Seems that you forgot the output file name.

Yes, I know that the argument parsing is sometimes not very forgiving.

Hope this helps.

**Comment by paul1149** [comment]
Hi,
Thanks for the quick response. I didn't see the need for an output name in the instructions. I did find a similar error in closed issues here, and saw you advice to add the output name. I tried to get the syntax, but got this:

$ java -jar BMC.jar help <ExportFormat/Tool>
bash: syntax error near unexpected token `newline'

So I went ahead and simply added the output file name, k16.SQLite3, and it seems to have worked perfectly.

I'd be interested in accessing the help file. I didn't see it online here either.

Thanks much. I appreciate this prog.

**Comment by schierlm** [comment]
Try

    $ java -jar BMC.jar help MyBibleZone

Hope this helps.

**Comment by paul1149** [comment]
That seems to have worked. Thanks again.

$ java -jar BMC.jar help MyBibleZone
MyBibleZone - MyBible.zone (Bible Reader for Android).

MyBible.zone (Bible Reader for Android).

Import: MyBibleZone <moduleName>.SQLite3
Export: MyBibleZone <moduleName>.SQLite3 [<propertyfile>]

Property file can be used for overriding values in the info table.
In case of footnotes, a .commentaries.SQLite3 file is read/written automatically.
