### ISSUE TITLE
Trouble Converting Beblia XML Format

### ISSUE THREAD

**Issue by davidicharp** [schierlm/BibleMultiConverter#91]
I am trying to convert Beblia XML to a standard Zenfania XML, but keep getting error messages. I tried every XML input setting and nothing works. The same error message appears when ZefaniaXMLRoundtrip  is selected as the export setting.

Here is the links to the two files I am trying to convert:
[https://github.com/Beblia/Holy-Bible-XML-Format/blob/master/EnglishCSBBible.xml](url)
[https://github.com/Beblia/Holy-Bible-XML-Format/blob/master/EnglishAmplifiedBible.xml](url)

java -jar BibleMultiConverter.jar RoundtripXML amp.xml RoundtripXML amp2.xml

WARNING: Schema validation failed:
        [Error] org.xml.sax.SAXParseException; systemId: file:/C:/Users/hallelujah/Desktop/Bible%20Converter/amp.xml; lineNumber: 2; columnNumber: 120; cvc-elt.1.a: Cannot find the declaration of element 'bible'.
WARNING: Parsing anyway after validation errors
Exception in thread "main" javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; systemId: file:/C:/Users/hallelujah/Desktop/Bible%20Converter/amp.xml; lineNumber: 2; columnNumber: 120; cvc-elt.1.a: Cannot find the declaration of element 'bible'.]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(Unknown Source)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:578)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:264)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:236)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:291)
        at biblemulticonverter.format.RoundtripXML.doImport(RoundtripXML.java:61)
        at biblemulticonverter.Main.main(Main.java:66)
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users/hallelujah/Desktop/Bible%20Converter/amp.xml; lineNumber: 2; columnNumber: 120; cvc-elt.1.a: Cannot find the declaration of element 'bible'.

**Comment by schierlm** [comment]
As input format, use `BebliaXML`.

Note that the latest binary release does not contain the BebliaXML import filter yet, so if you don't want to compile the code from the github repo, take the nightly version from https://nightly.link/schierlm/BibleMultiConverter/workflows/main.yaml/master/BibleMultiConverter-AllInOneEdition-Release.zip

Hope this helps. If not, please post the error when using this input format.
