### ISSUE TITLE
How to identify location of parsing error?

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#96]
Hi, I'm getting the following error for a translation of Acts:

```
Exception in thread "main" java.lang.RuntimeException: Failed parsing act.usfm
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportAllBooks(AbstractParatextFormat.java:514)
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportBooks(AbstractParatextFormat.java:438)
        at biblemulticonverter.tools.ParatextConverter.run(ParatextConverter.java:40)
        at biblemulticonverter.Main.main(Main.java:58)
Caused by: java.io.IOException: Could not insert verse end, because no suitable location could be found.
        at biblemulticonverter.format.paratext.utilities.ImportUtilities.closeOpenVerse(ImportUtilities.java:85)
        at biblemulticonverter.format.paratext.USFM.doImportBook(USFM.java:247)
        at biblemulticonverter.format.paratext.USFM.doImportBook(USFM.java:94)
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportAllBooks(AbstractParatextFormat.java:508)
        ... 3 more
```

This is the file causing the error:

[act.usfm.txt](https://github.com/user-attachments/files/18223888/act.usfm.txt)

It would be helpful to know what's wrong with the file. But also, is there a way to identify what line or chapter or verse the error is occurring in? For future issues.

**Comment by schierlm** [comment]
The verse that triggered this bug was Act 1:8.

In a553d4b9657def0d8dfa45ccdcdb312e3dea3dfc, when refactoring how VerseStart and VerseEnd are represented, I forgot to adjust USFM's verse end detection logic - in particular, if a verse was totally empty (no text and no paragraphs before/after), it did not consider to put the verse end after the empty character content of the verse (before, the character content included the VerseStart so it worked).

I will push a fix soon to both branches, that also adds the verse's location to the error message (not that it would helped much - you'd have seen the verse to be empty, but empty verses are valid in USFM and many other formats).
