### ISSUE TITLE
USX: Can't parse sid/eid which is a range of verses

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#97]
BMC currently throws when sid/eid is a range. E.g.:

`<verse number="10,11" style="v" sid="MAT 18:10,11"/>`

```
Exception in thread "main" java.lang.RuntimeException: Failed parsing mat.usx
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportAllBooks(AbstractParatextFormat.java:514)
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportBooks(AbstractParatextFormat.java:438)
        at biblemulticonverter.tools.ParatextConverter.run(ParatextConverter.java:40)
        at biblemulticonverter.Main.main(Main.java:58)
Caused by: java.io.IOException: java.lang.IllegalArgumentException: Given location string is not a valid verse location identifier: MAT 18:10,11
        at biblemulticonverter.format.paratext.USX3.handleVerse(USX3.java:518)
        at biblemulticonverter.format.paratext.USX3.parseCharContent(USX3.java:491)
        at biblemulticonverter.format.paratext.USX3.doImportBook(USX3.java:204)
        at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportAllBooks(AbstractParatextFormat.java:508)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Given location string is not a valid verse location identifier: MAT 18:10,11
        at biblemulticonverter.format.paratext.model.VerseIdentifier.fromStringOrThrow(VerseIdentifier.java:63)
        at biblemulticonverter.format.paratext.USX3.handleVerse(USX3.java:509)
        ... 6 more
```

It looks like old documentation for USX [appears to forbid](https://ubsicap.github.io/usx/elements.html#verse) a comma in the value. But even on that page they give an example such as:

`<verse number="18-19" style="v" pubnumber="1-2" sid="ESG 1:18-19" />`

And [more recent documentation](https://github.com/usfm-bible/tcdocs/blob/bfb15ab42a45762b86ba3776d353db19c870a046/grammar/usx.rng#L1804) has the following pattern for validation: `[A-Z1-4]{3} ?[‏a-z0-9,\-:\p{L}\p{Mn}]*`

**Comment by schierlm** [comment]
Thanks for the bug report.

Yes, the documentation about mixed verse ranges is a bit unclear. Allowed in @number for a longtime, but not in sid/eid. Seems they have rectified it. Other non-Paratext formats often support those, too. 

And, as you showed, they exist in real-world files, so I'd better support them.

Will push a fix that supports mixed verse ranges when converting between Paratext formats or from Paratext to non-Paratext format. Converting to Paratext format will stay as is (rewrite these references).
